(function(){
    var modules={
        "panel-main1":    			{url:"$H/m/panel-main1.html",router:1},
        "panel-main2":    			{url:"$H/m/panel-main2.html",router:1},
        "panel-child1":    			{url:"$H/m/panel-child1.html"},
        "panel-child2":    			{url:"$H/m/panel-child2.html"},
        
        "participant-data":   		{url:"$H/m/participant/participant-data.html",Table:"cleverlights-participant",form_module:"participant-form",router:1,
                                            child_panel1:"panel-child1",
                                            child_panel2:"panel-child2",
                                            questionnaire_setup:"online-questionnaire-setup-cleverlights",
                                            online_questionnaire:"online-questionnaire-app-cleverlights",
                                            participant_id:{field1:"Subject_ID",field2:"Subject_Initials"}
                                        },
        "participant-form":   		{url:"$H/m/participant/participant-form.html",Table:"cleverlights-participant"},

        "online-questionnaire-setup-cleverlights": 	{url:"$H/m/oq-setup.html",Table:"cleverlights-participant"},
        "online-questionnaire-app-cleverlights":    {url:"$H/oq.html"},

        "notes-data":  	                    {url:"$H/m/library/notes-data.html",Table:"cl-notes",form_module:"notes-form",router:1},
        "notes-form":  	                    {url:"$H/m/library/notes-form.html",Table:"cl-notes"},

        "cl-randomisation-table-data":		    {url:"$H/m/library/randomisation-table-data.html",Table:"cl-randomisation-table",form_module:"cl-randomisation-table-form"},
        "cl-randomisation-table-form":		    {url:"$H/m/library/randomisation-table-form.html",Table:"cl-randomisation-table"},
        "cl-randomisation-upload-data":		    {url:"$H/m/library/randomisation-upload-data.html",Table:"cl-randomisation-upload",form_module:"cl-randomisation-upload-form",task_name:"Randomisation Document"},
        "cl-randomisation-upload-form":		    {url:"$H/m/library/randomisation-upload-form.html",Table:"cl-randomisation-upload",task_name:"Randomisation Document"},
        "cl-concom-medication-data":            {url:"$H/m/library/concom-medication-data.html",Table:"cl-concom-medication",form_module:"cl-concom-medication-form",task_name:"Concom Medication"},
        "cl-concom-medication-form":            {url:"$H/m/library/concom-medication-form.html",Table:"cl-concom-medication"},
        "cl-adverse-event-data":                {url:"$H/m/library/adverse-event-data.html",Table:"cl-adverse-event",form_module:"cl-adverse-event-form",task_name:"Adverse Event"},
        "cl-adverse-event-form":                {url:"$H/m/library/adverse-event-form.html",Table:"cl-adverse-event"},
        "cl-medical-history-data":                {url:"$H/m/library/medical-history-data.html",Table:"cl-medical-history",form_module:"cl-medical-history-form",task_name:"Medical History"},
        "cl-medical-history-form":                {url:"$H/m/library/medical-history-form.html",Table:"cl-medical-history"},
        "cl-eligibility-confirmation-data":                {url:"$H/m/library/eligibility-confirmation-data.html",Table:"cl-eligibility-confirmation",form_module:"cl-eligibility-confirmation-form",task_name:"Eligibility Confirmation"},
        "cl-eligibility-confirmation-form":                {url:"$H/m/library/eligibility-confirmation-form.html",Table:"cl-eligibility-confirmation"},

        "cl-p1-eligibility-confirmation-part1-data":		            {url:"$H/m/library/eligibility-confirmation-part1-data.html",Table:"cl-p1-eligibility-confirmation-part1",form_module:"cl-p1-eligibility-confirmation-part1-form",task_name:"Part 1 - Eligibility Confirmation"},
        "cl-p1-eligibility-confirmation-part1-form":		            {url:"$H/m/library/eligibility-confirmation-part1-form.html",Table:"cl-p1-eligibility-confirmation-part1",task_name:"Eligibility Confirmation"},
        "cl-p1-pis-data":		            {url:"$H/m/library/pis-data.html",Table:"cl-p1-pis",form_module:"cl-p1-pis-form",task_name:"Part 1 - Participant Information Sheet"},
        "cl-p1-pis-form":		            {url:"$H/m/library/pis-form.html",Table:"cl-p1-pis",task_name:"Participant Information Sheet"},
        "cl-p1-consent-data":		            {url:"$H/m/library/consent-data.html",Table:"cl-p1-consent",form_module:"cl-p1-consent-form",task_name:"Part 1 - Consent Form"},
        "cl-p1-consent-form":		            {url:"$H/m/library/consent-form.html",Table:"cl-p1-consent",task_name:"Consent Form"},
        "cl-p1-ethnicity-data":		            {url:"$H/m/library/ethnicity-data.html",Table:"cl-p1-ethnicity",form_module:"cl-p1-ethnicity-form",task_name:"Part 1 - Ethnicity"},
        "cl-p1-ethnicity-form":		            {url:"$H/m/library/ethnicity-form.html",Table:"cl-p1-ethnicity",task_name:"Ethnicity"},
        "cl-p1-lifestyle-data":		            {url:"$H/m/library/lifestyle-data.html",Table:"cl-p1-lifestyle",form_module:"cl-p1-lifestyle-form",task_name:"Part 1 - Life Style"},
        "cl-p1-lifestyle-form":		            {url:"$H/m/library/lifestyle-form.html",Table:"cl-p1-lifestyle",task_name:"Lifestyle"},
        "cl-p1-education-data":		            {url:"$H/m/library/education-data.html",Table:"cl-p1-education",form_module:"cl-p1-education-form",task_name:"Part 1 - Education"},
        "cl-p1-education-form":		            {url:"$H/m/library/education-form.html",Table:"cl-p1-education",task_name:"Education"},
        "cl-p1-sf36-data":		            {url:"$H/m/library/sf36-data.html",Table:"cl-p1-sf36",form_module:"cl-p1-sf36-form",task_name:"Part 1 - SF36"},
        "cl-p1-sf36-form":		            {url:"$H/m/library/sf36-form.html",Table:"cl-p1-sf36",task_name:"SF36"},
        "cl-p1-hads-data":		            {url:"$H/m/library/hads-data.html",Table:"cl-p1-hads",form_module:"cl-p1-hads-form",task_name:"Part 1 - HADS"},
        "cl-p1-hads-form":		            {url:"$H/m/library/hads-form.html",Table:"cl-p1-hads",task_name:"HADS"},
        "cl-p1-me-data":		            {url:"$H/m/library/me-data.html",Table:"cl-p1-me",form_module:"cl-p1-me-form",task_name:"Part 1 - Morning Evening Questionnaire"},
        "cl-p1-me-form":		            {url:"$H/m/library/me-form.html",Table:"cl-p1-me",task_name:"Morning Evening Questionnaire"},
        "cl-p1-ess-data":		            {url:"$H/m/library/ess-data.html",Table:"cl-p1-ess",form_module:"cl-p1-ess-form",task_name:"Part 1 - ESS"},
        "cl-p1-ess-form":		            {url:"$H/m/library/ess-form.html",Table:"cl-p1-ess",task_name:"ESS"},
        "cl-p1-isi-data":		            {url:"$H/m/library/isi-data.html",Table:"cl-p1-isi",form_module:"cl-p1-isi-form",task_name:"Part 1 - ISI"},
        "cl-p1-isi-form":		            {url:"$H/m/library/isi-form.html",Table:"cl-p1-isi",task_name:"ISI"},
        "cl-p1-psqi-data":		            {url:"$H/m/library/psqi-data.html",Table:"cl-p1-psqi",form_module:"cl-p1-psqi-form",task_name:"Part 1 - PSQI"},
        "cl-p1-psqi-form":		            {url:"$H/m/library/psqi-form.html",Table:"cl-p1-psqi",task_name:"PSQI"},
        "cl-p1-map-data":		            {url:"$H/m/library/map-data.html",Table:"cl-p1-map",form_module:"cl-p1-map-form",task_name:"Part 1 - MAP"},
        "cl-p1-map-form":		            {url:"$H/m/library/map-form.html",Table:"cl-p1-map",task_name:"MAP"},
        "cl-p1-actigraphy-data":		            {url:"$H/m/library/actigraphy-data.html",Table:"cl-p1-actigraphy",form_module:"cl-p1-actigraphy-form",task_name:"Part 1 - Actigraphy"},
        "cl-p1-actigraphy-form":		            {url:"$H/m/library/actigraphy-form.html",Table:"cl-p1-actigraphy",task_name:"Actigraphy"},
        "cl-p1-light-sensor-data":		            {url:"$H/m/library/light-sensor-data.html",Table:"cl-p1-light-sensor",form_module:"cl-p1-light-sensor-form",task_name:"Part 1 - Light Sensor"},
        "cl-p1-light-sensor-form":		            {url:"$H/m/library/light-sensor-form.html",Table:"cl-p1-light-sensor",task_name:"Light Sensor"},

        "cl-s-telephone-screening-data":		                {url:"$H/m/library/telephone-screening-data.html",Table:"cl-s-telephone-screening",form_module:"cl-s-telephone-screening-form",task_name:"Screening - Telephone screening"},
        "cl-s-telephone-screening-form":		                {url:"$H/m/library/telephone-screening-form.html",Table:"cl-s-telephone-screening"},
        "cl-s-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-s-date",form_module:"cl-s-date-form",task_name:"Screening - Date"},
        "cl-s-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-s-date"},
        "cl-s-anthropometry-data":		            {url:"$H/m/library/anthropometry-data.html",Table:"cl-s-anthropometry",form_module:"cl-s-anthropometry-form",task_name:"Screening - Anthropometry"},
        "cl-s-anthropometry-form":		            {url:"$H/m/library/anthropometry-form.html",Table:"cl-s-anthropometry"},
        "cl-s-include-exclude-data":		            {url:"$H/m/library/inclusion-exclusion-data.html",Table:"cl-s-include-exclude",form_module:"cl-s-include-exclude-form",task_name:"Screening - Includsion/Exclusion Criteria"},
        "cl-s-include-exclude-form":		            {url:"$H/m/library/inclusion-exclusion-form.html",Table:"cl-s-include-exclude"},
        "cl-s-mmse-1-data":		            {url:"$H/m/library/mmse-data.html",Table:"cl-s-mmse-1",form_module:"cl-s-mmse-1-form",task_name:"Screening - MMSE"},
        "cl-s-mmse-1-form":		            {url:"$H/m/library/mmse-form.html",Table:"cl-s-mmse-1"},
        "cl-s-mmse-2-data":		            {url:"$H/m/library/mmse-data.html",Table:"cl-s-mmse-2",form_module:"cl-s-mmse-2-form",task_name:"Screening - MMSE double entry"},
        "cl-s-mmse-2-form":		            {url:"$H/m/library/mmse-form.html",Table:"cl-s-mmse-2"},
        "cl-s-mmse-upload-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-s-mmse-upload",form_module:"cl-s-mmse-upload-form",task_name:"Screening - MMSE file upload"},
        "cl-s-mmse-upload-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-s-mmse-upload",task_name:"Screening - MMSE file upload"},
        "cl-s-psg300-data":		            {url:"$H/m/library/psg300-data.html",Table:"cl-s-psg300",form_module:"cl-s-psg300-form",task_name:"Screening - PSG"},
        "cl-s-psg300-form":		            {url:"$H/m/library/psg300-form.html",Table:"cl-s-psg300"},
        "cl-s-sleep-scoring-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-s-sleep-scoring",form_module:"cl-s-sleep-scoring-form",task_name:"Screening - PSG Sleep Scoring"},
        "cl-s-sleep-scoring-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-s-sleep-scoring",task_name:"Screening - PSG Sleep Scoring"},
        "cl-s-edf-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-s-edf",form_module:"cl-s-edf-form",task_name:"Screening - PSG EDF"},
        "cl-s-edf-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-s-edf",task_name:"Screening - PSG EDF"},
        "cl-s-wristox-data":		                {url:"$H/m/library/wristox-data.html",Table:"cl-s-wristox",form_module:"cl-s-wristox-form",task_name:"Baseline - WristOx"},
        "cl-s-wristox-form":		                {url:"$H/m/library/wristox-form.html",Table:"cl-s-wristox",task_name:"WristOx Baseline"},
        "cl-bl-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-bl-date",form_module:"cl-bl-date-form",task_name:"Baseline - Date"},
        "cl-bl-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-bl-date"},
        "cl-bl-actigraphy-data":		            {url:"$H/m/library/actigraphy-data.html",Table:"cl-bl-actigraphy",form_module:"cl-bl-actigraphy-form",task_name:"Baseline - Actigraphy"},
        "cl-bl-actigraphy-form":		            {url:"$H/m/library/actigraphy-form.html",Table:"cl-bl-actigraphy",task_name:"Actigraphy"},
        "cl-bl-ethnicity-data":		            {url:"$H/m/library/ethnicity-data.html",Table:"cl-bl-ethnicity",form_module:"cl-bl-ethnicity-form",task_name:"Baseline - Ethnicity"},
        "cl-bl-ethnicity-form":		            {url:"$H/m/library/ethnicity-form.html",Table:"cl-bl-ethnicity",task_name:"Ethnicity"},
        "cl-bl-ksd-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-bl-ksd",form_module:"cl-bl-ksd-form",task_name:"Baseline - Karolinska Sleep Diary - File Upload"},
        "cl-bl-ksd-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-bl-ksd",task_name:"Karolinska Sleep Diary - File Upload"},
        "cl-bl-ksd1-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-bl-ksd1",form_module:"cl-bl-ksd1-form",task_name:"Baseline - Karolinska Sleep Diary Night 1"},
        "cl-bl-ksd1-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-bl-ksd1",task_name:"Karolinska Sleep Diary Night 1"},
        "cl-bl-ksd2-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-bl-ksd2",form_module:"cl-bl-ksd2-form",task_name:"Baseline - Karolinska Sleep Diary Night 2"},
        "cl-bl-ksd2-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-bl-ksd2",task_name:"Karolinska Sleep Diary Night 2"},
        "cl-bl-ksd3-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-bl-ksd3",form_module:"cl-bl-ksd3-form",task_name:"Baseline - Karolinska Sleep Diary Night 3"},
        "cl-bl-ksd3-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-bl-ksd3",task_name:"Karolinska Sleep Diary Night 3"},
        "cl-bl-ksd4-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-bl-ksd4",form_module:"cl-bl-ksd4-form",task_name:"Baseline - Karolinska Sleep Diary Night 4"},
        "cl-bl-ksd4-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-bl-ksd4",task_name:"Karolinska Sleep Diary Night 4"},
        "cl-bl-ksd5-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-bl-ksd5",form_module:"cl-bl-ksd5-form",task_name:"Baseline - Karolinska Sleep Diary Night 5"},
        "cl-bl-ksd5-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-bl-ksd5",task_name:"Karolinska Sleep Diary Night 5"},
        "cl-bl-ksd6-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-bl-ksd6",form_module:"cl-bl-ksd6-form",task_name:"Baseline - Karolinska Sleep Diary Night 6"},
        "cl-bl-ksd6-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-bl-ksd6",task_name:"Karolinska Sleep Diary Night 6"},
        "cl-bl-ksd7-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-bl-ksd7",form_module:"cl-bl-ksd7-form",task_name:"Baseline - Karolinska Sleep Diary Night 7"},
        "cl-bl-ksd7-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-bl-ksd7",task_name:"Karolinska Sleep Diary Night 7"},
        "cl-bl-lifestyle-data":		            {url:"$H/m/library/lifestyle-data.html",Table:"cl-bl-lifestyle",form_module:"cl-bl-lifestyle-form",task_name:"Baseline - Life Style"},
        "cl-bl-lifestyle-form":		            {url:"$H/m/library/lifestyle-form.html",Table:"cl-bl-lifestyle",task_name:"Lifestyle"},
        "cl-bl-education-data":		            {url:"$H/m/library/education-data.html",Table:"cl-bl-education",form_module:"cl-bl-education-form",task_name:"Baseline - Education"},
        "cl-bl-education-form":		            {url:"$H/m/library/education-form.html",Table:"cl-bl-education",task_name:"Education"},
        "cl-bl-wtar-1-data":		            {url:"$H/m/library/wtar-data.html",Table:"cl-bl-wtar-1",form_module:"cl-bl-wtar-1-form",task_name:"Baseline - WTAR-1"},
        "cl-bl-wtar-1-form":		            {url:"$H/m/library/wtar-form.html",Table:"cl-bl-wtar-1",task_name:"WTAR-1"},
        "cl-bl-wtar-2-data":		            {url:"$H/m/library/wtar-data.html",Table:"cl-bl-wtar-2",form_module:"cl-bl-wtar-2-form",task_name:"Baseline - WTAR-2"},
        "cl-bl-wtar-2-form":		            {url:"$H/m/library/wtar-form.html",Table:"cl-bl-wtar-2",task_name:"WTAR-2"},
        "cl-bl-wtar-upload-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-bl-wtar-upload",form_module:"cl-bl-wtar-upload-form",task_name:"Baseline - WTAR Upload File"},
        "cl-bl-wtar-upload-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-bl-wtar-upload",task_name:"Baseline - WTAR Upload File"},
        "cl-bl-genotype-data":		            {url:"$H/m/library/genotype-data.html",Table:"cl-bl-genotype",form_module:"cl-bl-genotype-form",task_name:"Baseline - Genotype"},
        "cl-bl-genotype-form":		            {url:"$H/m/library/genotype-form.html",Table:"cl-bl-genotype"},
        "cl-bl-ess-data":		                {url:"$H/m/library/ess-data.html",Table:"cl-bl-ess",form_module:"cl-bl-ess-form",task_name:"Baseline - ESS"},
        "cl-bl-ess-form":		                {url:"$H/m/library/ess-form.html",Table:"cl-bl-ess",task_name:"ESS"},
        "cl-bl-dass-data":		                {url:"$H/m/library/dass-data.html",Table:"cl-bl-dass",form_module:"cl-bl-dass-form",task_name:"Baseline - DASS"},
        "cl-bl-dass-form":		                {url:"$H/m/library/dass-form.html",Table:"cl-bl-dass",task_name:"DASS"},
        "cl-bl-sf36-data":		                {url:"$H/m/library/sf36-data.html",Table:"cl-bl-sf36",form_module:"cl-bl-sf36-form",task_name:"Baseline - SF36"},
        "cl-bl-sf36-form":		                {url:"$H/m/library/sf36-form.html",Table:"cl-bl-sf36",task_name:"SF36"},
        "cl-bl-me-data":		                    {url:"$H/m/library/me-data.html",Table:"cl-bl-me",form_module:"cl-bl-me-form",task_name:"Baseline - ME"},
        "cl-bl-me-form":		                    {url:"$H/m/library/me-form.html",Table:"cl-bl-me",task_name:"Morningness-Eveningness Questionnaire"},
        "cl-bl-hads-data":		                {url:"$H/m/library/hads-data.html",Table:"cl-bl-hads",form_module:"cl-bl-hads-form",task_name:"Baseline - HADS"},
        "cl-bl-hads-form":		                {url:"$H/m/library/hads-form.html",Table:"cl-bl-hads",task_name:"HADS"},

        "cl-v1-d1-t1-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d1-t1-kss",form_module:"cl-v1-d1-t1-kss-form",task_name:"Lab Visit 1 Day 1 - KSS 1"},
        "cl-v1-d1-t1-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d1-t1-kss",task_name:"KSS 1"},
        "cl-v1-d1-t1-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d1-t1-pvt",form_module:"cl-v1-d1-t1-pvt-form",task_name:"Lab Visit 1 Day 1 - PVT 1"},
        "cl-v1-d1-t1-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d1-t1-pvt"},
        "cl-v1-d1-t2-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d1-t2-kss",form_module:"cl-v1-d1-t2-kss-form",task_name:"Lab Visit 1 Day 1 - KSS 2"},
        "cl-v1-d1-t2-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d1-t2-kss",task_name:"KSS 2"},
        "cl-v1-d1-t2-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d1-t2-pvt",form_module:"cl-v1-d1-t2-pvt-form",task_name:"Lab Visit 1 Day 1 - PVT 2"},
        "cl-v1-d1-t2-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d1-t2-pvt"},
        "cl-v1-d1-t3-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d1-t3-kss",form_module:"cl-v1-d1-t3-kss-form",task_name:"Lab Visit 1 Day 1 - KSS 3"},
        "cl-v1-d1-t3-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d1-t3-kss",task_name:"KSS 3"},
        "cl-v1-d1-t3-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d1-t3-pvt",form_module:"cl-v1-d1-t3-pvt-form",task_name:"Lab Visit 1 Day 1 - PVT 3"},
        "cl-v1-d1-t3-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d1-t3-pvt"},
        "cl-v1-d1-t4-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d1-t4-kss",form_module:"cl-v1-d1-t4-kss-form",task_name:"Lab Visit 1 Day 1 - KSS 4"},
        "cl-v1-d1-t4-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d1-t4-kss",task_name:"KSS 4"},
        "cl-v1-d1-t4-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d1-t4-pvt",form_module:"cl-v1-d1-t4-pvt-form",task_name:"Lab Visit 1 Day 1 - PVT 4"},
        "cl-v1-d1-t4-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d1-t4-pvt"},
        "cl-v1-d1-t5-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d1-t5-kss",form_module:"cl-v1-d1-t5-kss-form",task_name:"Lab Visit 1 Day 1 - KSS 5"},
        "cl-v1-d1-t5-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d1-t5-kss",task_name:"KSS 5"},
        "cl-v1-d1-t5-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d1-t5-pvt",form_module:"cl-v1-d1-t5-pvt-form",task_name:"Lab Visit 1 Day 1 - PVT 5"},
        "cl-v1-d1-t5-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d1-t5-pvt"},
        "cl-v1-d2-t1-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d2-t1-kss",form_module:"cl-v1-d2-t1-kss-form",task_name:"Lab Visit 1 Day 2 - KSS 1"},
        "cl-v1-d2-t1-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d2-t1-kss",task_name:"KSS 1"},
        "cl-v1-d2-t1-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d2-t1-pvt",form_module:"cl-v1-d2-t1-pvt-form",task_name:"Lab Visit 1 Day 2 - PVT 1"},
        "cl-v1-d2-t1-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d2-t1-pvt"},
        "cl-v1-d2-t2-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d2-t2-kss",form_module:"cl-v1-d2-t2-kss-form",task_name:"Lab Visit 1 Day 2 - KSS 2"},
        "cl-v1-d2-t2-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d2-t2-kss",task_name:"KSS 2"},
        "cl-v1-d2-t2-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d2-t2-pvt",form_module:"cl-v1-d2-t2-pvt-form",task_name:"Lab Visit 1 Day 2 - PVT 2"},
        "cl-v1-d2-t2-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d2-t2-pvt"},
        "cl-v1-d2-t3-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d2-t3-kss",form_module:"cl-v1-d2-t3-kss-form",task_name:"Lab Visit 1 Day 2 - KSS 3"},
        "cl-v1-d2-t3-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d2-t3-kss",task_name:"KSS 3"},
        "cl-v1-d2-t3-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d2-t3-pvt",form_module:"cl-v1-d2-t3-pvt-form",task_name:"Lab Visit 1 Day 2 - PVT 3"},
        "cl-v1-d2-t3-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d2-t3-pvt"},
        "cl-v1-d2-t4-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d2-t4-kss",form_module:"cl-v1-d2-t4-kss-form",task_name:"Lab Visit 1 Day 2 - KSS 4"},
        "cl-v1-d2-t4-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d2-t4-kss",task_name:"KSS 4"},
        "cl-v1-d2-t4-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d2-t4-pvt",form_module:"cl-v1-d2-t4-pvt-form",task_name:"Lab Visit 1 Day 2 - PVT 4"},
        "cl-v1-d2-t4-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d2-t4-pvt"},
        "cl-v1-d2-t5-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d2-t5-kss",form_module:"cl-v1-d2-t5-kss-form",task_name:"Lab Visit 1 Day 2 - KSS 5"},
        "cl-v1-d2-t5-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d2-t5-kss",task_name:"KSS 5"},
        "cl-v1-d2-t5-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d2-t5-pvt",form_module:"cl-v1-d2-t5-pvt-form",task_name:"Lab Visit 1 Day 2 - PVT 5"},
        "cl-v1-d2-t5-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d2-t5-pvt"},
        "cl-v1-d2-t6-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d2-t6-kss",form_module:"cl-v1-d2-t6-kss-form",task_name:"Lab Visit 1 Day 2 - KSS 6"},
        "cl-v1-d2-t6-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d2-t6-kss",task_name:"KSS 6"},
        "cl-v1-d2-t6-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d2-t6-pvt",form_module:"cl-v1-d2-t6-pvt-form",task_name:"Lab Visit 1 Day 2 - PVT 6"},
        "cl-v1-d2-t6-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d2-t6-pvt"},
        "cl-v1-d2-t7-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d2-t7-kss",form_module:"cl-v1-d2-t7-kss-form",task_name:"Lab Visit 1 Day 2 - KSS 7"},
        "cl-v1-d2-t7-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d2-t7-kss",task_name:"KSS 7"},
        "cl-v1-d2-t7-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d2-t7-pvt",form_module:"cl-v1-d2-t7-pvt-form",task_name:"Lab Visit 1 Day 2 - PVT 7"},
        "cl-v1-d2-t7-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d2-t7-pvt"},
        "cl-v1-d3-t1-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d3-t1-kss",form_module:"cl-v1-d3-t1-kss-form",task_name:"Lab Visit 1 Day 3 - KSS 1"},
        "cl-v1-d3-t1-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d3-t1-kss",task_name:"KSS 1"},
        "cl-v1-d3-t1-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d3-t1-pvt",form_module:"cl-v1-d3-t1-pvt-form",task_name:"Lab Visit 1 Day 3 - PVT 1"},
        "cl-v1-d3-t1-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d3-t1-pvt"},
        "cl-v1-d3-t2-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d3-t2-kss",form_module:"cl-v1-d3-t2-kss-form",task_name:"Lab Visit 1 Day 3 - KSS 2"},
        "cl-v1-d3-t2-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d3-t2-kss",task_name:"KSS 2"},
        "cl-v1-d3-t2-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d3-t2-pvt",form_module:"cl-v1-d3-t2-pvt-form",task_name:"Lab Visit 1 Day 3 - PVT 2"},
        "cl-v1-d3-t2-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d3-t2-pvt"},
        "cl-v1-d3-t3-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d3-t3-kss",form_module:"cl-v1-d3-t3-kss-form",task_name:"Lab Visit 1 Day 3 - KSS 3"},
        "cl-v1-d3-t3-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d3-t3-kss",task_name:"KSS 3"},
        "cl-v1-d3-t3-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d3-t3-pvt",form_module:"cl-v1-d3-t3-pvt-form",task_name:"Lab Visit 1 Day 3 - PVT 3"},
        "cl-v1-d3-t3-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d3-t3-pvt"},
        "cl-v1-d3-t4-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d3-t4-kss",form_module:"cl-v1-d3-t4-kss-form",task_name:"Lab Visit 1 Day 3 - KSS 4"},
        "cl-v1-d3-t4-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d3-t4-kss",task_name:"KSS 4"},
        "cl-v1-d3-t4-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d3-t4-pvt",form_module:"cl-v1-d3-t4-pvt-form",task_name:"Lab Visit 1 Day 3 - PVT 4"},
        "cl-v1-d3-t4-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d3-t4-pvt"},
        "cl-v1-d3-t5-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d3-t5-kss",form_module:"cl-v1-d3-t5-kss-form",task_name:"Lab Visit 1 Day 3 - KSS 5"},
        "cl-v1-d3-t5-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d3-t5-kss",task_name:"KSS 5"},
        "cl-v1-d3-t5-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d3-t5-pvt",form_module:"cl-v1-d3-t5-pvt-form",task_name:"Lab Visit 1 Day 3 - PVT 5"},
        "cl-v1-d3-t5-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d3-t5-pvt"},
        "cl-v1-d3-t7-kdt-data":		            {url:"$H/m/library/file-location-data.html",Table:"cl-v1-d3-t7-kdt",form_module:"cl-v1-d3-t7-kdt-form",task_name:"Lab Visit 1 Day 3 - KDT 5"},
        "cl-v1-d3-t7-kdt-form":		            {url:"$H/m/library/file-location-form.html",Table:"cl-v1-d3-t7-kdt",task_name:"HdEEG KDT - Scoring report"},
        "cl-v1-d3-t6-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d3-t6-kss",form_module:"cl-v1-d3-t6-kss-form",task_name:"Lab Visit 1 Day 3 - KSS 6"},
        "cl-v1-d3-t6-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d3-t6-kss",task_name:"KSS 6"},
        "cl-v1-d3-t6-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d3-t6-pvt",form_module:"cl-v1-d3-t6-pvt-form",task_name:"Lab Visit 1 Day 3 - PVT 6"},
        "cl-v1-d3-t6-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d3-t6-pvt"},
        "cl-v1-d3-t7-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d3-t7-kss",form_module:"cl-v1-d3-t7-kss-form",task_name:"Lab Visit 1 Day 3 - KSS 7"},
        "cl-v1-d3-t7-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d3-t7-kss",task_name:"KSS 7"},
        "cl-v1-d3-t7-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d3-t7-pvt",form_module:"cl-v1-d3-t7-pvt-form",task_name:"Lab Visit 1 Day 3 - PVT 7"},
        "cl-v1-d3-t7-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d3-t7-pvt"},
        "cl-v1-d4-t1-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v1-d4-t1-kss",form_module:"cl-v1-d4-t1-kss-form",task_name:"Lab Visit 1 Day 3 - KSS 1"},
        "cl-v1-d4-t1-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v1-d4-t1-kss",task_name:"KSS 1"},
        "cl-v1-d4-t1-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v1-d4-t1-pvt",form_module:"cl-v1-d4-t1-pvt-form",task_name:"Lab Visit 1 Day 3 - PVT 1"},
        "cl-v1-d4-t1-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v1-d4-t1-pvt"},
        "cl-v1-d4-t1-kdt-data":		            {url:"$H/m/library/file-location-data.html",Table:"cl-v1-d4-t1-kdt",form_module:"cl-v1-d4-t1-kdt-form",task_name:"Lab Visit 1 Day 3 - KDT 1"},
        "cl-v1-d4-t1-kdt-form":		            {url:"$H/m/library/file-location-form.html",Table:"cl-v1-d4-t1-kdt",task_name:"HdEEG KDT - Scoring report"},

        "cl-v1-d1-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-v1-d1-date",form_module:"cl-v1-d1-date-form",task_name:"Lab Visit 1 Day 1 - Date"},
        "cl-v1-d1-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-v1-d1-date"},

        "cl-v1-d1-nt-bsrt-data":		        {url:"$H/m/library/bsrt-data.html",Table:"cl-v1-d1-nt-bsrt",form_module:"cl-v1-d1-nt-bsrt-form",task_name:"Lab Visit 1 Day 1 Neurocog Testing - BSRT Set 1"},
        "cl-v1-d1-nt-bsrt-form":		        {url:"$H/m/library/bsrt-form.html",Table:"cl-v1-d1-nt-bsrt"},
        "cl-v1-d1-nt-lct-data":		            {url:"$H/m/neurocog/letter-cancellation-data.html",Table:"cl-v1-d1-nt-lct",form_module:"cl-v1-d1-nt-lct-form",task_name:"Lab Visit 1 Day 1 Neurocog Testing - LCT"},
        "cl-v1-d1-nt-lct-form":		            {url:"$H/m/neurocog/letter-cancellation-form.html",Table:"cl-v1-d1-nt-lct",task_name:"LCT"},
        "cl-v1-d1-nt-nback2-data":		        {url:"$H/m/neurocog/nback2-data.html",Table:"cl-v1-d1-nt-nback2",form_module:"cl-v1-d1-nt-nback2-form",task_name:"Lab Visit 1 Day 1 Neurocog Testing - 2-Back"},
        "cl-v1-d1-nt-nback2-form":		        {url:"$H/m/neurocog/nback2-form.html",Table:"cl-v1-d1-nt-nback2",task_name:"2-Back"},
        "cl-v1-d1-nt-dsst-data":		        {url:"$H/m/neurocog/dsst-data.html",Table:"cl-v1-d1-nt-dsst",form_module:"cl-v1-d1-nt-dsst-form",task_name:"Lab Visit 1 Day 1 Neurocog Testing - SDMT"},
        "cl-v1-d1-nt-dsst-form":		        {url:"$H/m/neurocog/dsst-form.html",Table:"cl-v1-d1-nt-dsst",task_name:"SDMT"},
        "cl-v1-d1-nt-stroop-text-data":		    {url:"$H/m/neurocog/stroop-text-data.html",Table:"cl-v1-d1-nt-stroop-text",form_module:"cl-v1-d1-nt-stroop-text-form",task_name:"Lab Visit 1 Day 1 Neurocog Testing - Stroop Text"},
        "cl-v1-d1-nt-stroop-text-form":		    {url:"$H/m/neurocog/stroop-text-form.html",Table:"cl-v1-d1-nt-stroop-text",task_name:"Stroop Text"},
        "cl-v1-d1-nt-stroop-colour-data":		{url:"$H/m/neurocog/stroop-colour-data.html",Table:"cl-v1-d1-nt-stroop-colour",form_module:"cl-v1-d1-nt-stroop-colour-form",task_name:"Lab Visit 1 Day 1 Neurocog Testing - Stroop Colour"},
        "cl-v1-d1-nt-stroop-colour-form":		{url:"$H/m/neurocog/stroop-colour-form.html",Table:"cl-v1-d1-nt-stroop-colour",task_name:"Stroop Colour"},
        "cl-v1-d1-nt-ftt-data":		            {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"cl-v1-d1-nt-ftt",form_module:"cl-v1-d1-nt-ftt-form",task_name:"Lab Visit 1 Day 1 Neurocog Testing - FTT (6 mins)"},
        "cl-v1-d1-nt-ftt-form":		            {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"cl-v1-d1-nt-ftt",task_name:"FFT (6 mins)"},

        "cl-v1-d2-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-v1-d2-date",form_module:"cl-v1-d2-date-form",task_name:"Lab Visit 1 Day 2 - Date"},
        "cl-v1-d2-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-v1-d2-date"},
        "cl-v1-d2-ksd-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-v1-d2-ksd",form_module:"cl-v1-d2-ksd-form",task_name:"Lab Visit 1 Day 2 - Karolinska Sleep Diary - File Upload"},
        "cl-v1-d2-ksd-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-v1-d2-ksd",task_name:"Karolinska Sleep Diary - File Upload"},
        "cl-v1-d2-ksd1-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-v1-d2-ksd1",form_module:"cl-v1-d2-ksd1-form",task_name:"Lab Visit 1 Day 2 - Karolinska Sleep Diary"},
        "cl-v1-d2-ksd1-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-v1-d2-ksd1",task_name:"Karolinska Sleep Diary"},

        "cl-v1-d3-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-v1-d3-date",form_module:"cl-v1-d3-date-form",task_name:"Lab Visit 1 Day 3 - Date"},
        "cl-v1-d3-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-v1-d3-date"},
        "cl-v1-d3-ksd-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-v1-d3-ksd",form_module:"cl-v1-d3-ksd-form",task_name:"Lab Visit 1 Day 3 - Karolinska Sleep Diary - File Upload"},
        "cl-v1-d3-ksd-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-v1-d3-ksd",task_name:"Karolinska Sleep Diary - File Upload"},
        "cl-v1-d3-ksd1-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-v1-d3-ksd1",form_module:"cl-v1-d3-ksd1-form",task_name:"Lab Visit 1 Day 3 - Karolinska Sleep Diary"},
        "cl-v1-d3-ksd1-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-v1-d3-ksd1",task_name:"Karolinska Sleep Diary"},

        "cl-v1-d3-ntm-lct-data":		            {url:"$H/m/neurocog/letter-cancellation-data.html",Table:"cl-v1-d3-ntm-lct",form_module:"cl-v1-d3-ntm-lct-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - LCT"},
        "cl-v1-d3-ntm-lct-form":		            {url:"$H/m/neurocog/letter-cancellation-form.html",Table:"cl-v1-d3-ntm-lct",task_name:"LCT"},
        "cl-v1-d3-ntm-nback2-data":		        {url:"$H/m/neurocog/nback2-data.html",Table:"cl-v1-d3-ntm-nback2",form_module:"cl-v1-d3-ntm-nback2-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - 2-Back"},
        "cl-v1-d3-ntm-nback2-form":		        {url:"$H/m/neurocog/nback2-form.html",Table:"cl-v1-d3-ntm-nback2",task_name:"2-Back"},
        "cl-v1-d3-ntm-dsst-data":		        {url:"$H/m/neurocog/dsst-data.html",Table:"cl-v1-d3-ntm-dsst",form_module:"cl-v1-d3-ntm-dsst-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - SDMT"},
        "cl-v1-d3-ntm-dsst-form":		        {url:"$H/m/neurocog/dsst-form.html",Table:"cl-v1-d3-ntm-dsst",task_name:"SDMT"},
        "cl-v1-d3-ntm-stroop-text-data":		    {url:"$H/m/neurocog/stroop-text-data.html",Table:"cl-v1-d3-ntm-stroop-text",form_module:"cl-v1-d3-ntm-stroop-text-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - Stroop Text"},
        "cl-v1-d3-ntm-stroop-text-form":		    {url:"$H/m/neurocog/stroop-text-form.html",Table:"cl-v1-d3-ntm-stroop-text",task_name:"Stroop Text"},
        "cl-v1-d3-ntm-stroop-colour-data":		{url:"$H/m/neurocog/stroop-colour-data.html",Table:"cl-v1-d3-ntm-stroop-colour",form_module:"cl-v1-d3-ntm-stroop-colour-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - Stroop Colour"},
        "cl-v1-d3-ntm-stroop-colour-form":		{url:"$H/m/neurocog/stroop-colour-form.html",Table:"cl-v2-d3-ntm-stroop-colour",task_name:"Stroop Colour"},

        "cl-v1-d3-nt-bsrt2-data":		        {url:"$H/m/library/bsrt-data.html",Table:"cl-v1-d3-nt-bsrt",form_module:"cl-v1-d3-nt-bsrt2-form",task_name:"Lab Visit 1 Day 3 Neurocog Testing - BSRT Set 2"},
        "cl-v1-d3-nt-bsrt2-form":		        {url:"$H/m/library/bsrt2-form.html",Table:"cl-v1-d3-nt-bsrt"},
        "cl-v1-d3-nt-lct-data":		            {url:"$H/m/neurocog/letter-cancellation-data.html",Table:"cl-v1-d3-nt-lct",form_module:"cl-v1-d3-nt-lct-form",task_name:"Lab Visit 1 Day 3 Neurocog Testing - LCT"},
        "cl-v1-d3-nt-lct-form":		            {url:"$H/m/neurocog/letter-cancellation-form.html",Table:"cl-v1-d3-nt-lct",task_name:"LCT"},
        "cl-v1-d3-nt-nback2-data":		        {url:"$H/m/neurocog/nback2-data.html",Table:"cl-v1-d3-nt-nback2",form_module:"cl-v1-d3-nt-nback2-form",task_name:"Lab Visit 1 Day 3 Neurocog Testing - 2-Back"},
        "cl-v1-d3-nt-nback2-form":		        {url:"$H/m/neurocog/nback2-form.html",Table:"cl-v1-d3-nt-nback2",task_name:"2-Back"},
        "cl-v1-d3-nt-dsst-data":		        {url:"$H/m/neurocog/dsst-data.html",Table:"cl-v1-d3-nt-dsst",form_module:"cl-v1-d3-nt-dsst-form",task_name:"Lab Visit 1 Day 3 Neurocog Testing - SDMT"},
        "cl-v1-d3-nt-dsst-form":		        {url:"$H/m/neurocog/dsst-form.html",Table:"cl-v1-d3-nt-dsst",task_name:"SDMT"},
        "cl-v1-d3-nt-stroop-text-data":		    {url:"$H/m/neurocog/stroop-text-data.html",Table:"cl-v1-d3-nt-stroop-text",form_module:"cl-v1-d3-nt-stroop-text-form",task_name:"Lab Visit 1 Day 3 Neurocog Testing - Stroop Text"},
        "cl-v1-d3-nt-stroop-text-form":		    {url:"$H/m/neurocog/stroop-text-form.html",Table:"cl-v1-d3-nt-stroop-text",task_name:"Stroop Text"},
        "cl-v1-d3-nt-stroop-colour-data":		{url:"$H/m/neurocog/stroop-colour-data.html",Table:"cl-v1-d3-nt-stroop-colour",form_module:"cl-v1-d3-nt-stroop-colour-form",task_name:"Lab Visit 1 Day 3 Neurocog Testing - Stroop Colour"},
        "cl-v1-d3-nt-stroop-colour-form":		{url:"$H/m/neurocog/stroop-colour-form.html",Table:"cl-v1-d3-nt-stroop-colour",task_name:"Stroop Colour"},
        "cl-v1-d3-nt-ftt-data":		            {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"cl-v1-d3-nt-ftt",form_module:"cl-v1-d3-nt-ftt-form",task_name:"Lab Visit 1 Day 3 Neurocog Testing - FTT (12 mins)"},
        "cl-v1-d3-nt-ftt-form":		            {url:"$H/m/neurocog/finger-tapping12-before-form.html",Table:"cl-v1-d3-nt-ftt",task_name:"FFT (12 mins)"},

        "cl-v1-d4-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-v1-d4-date",form_module:"cl-v1-d4-date-form",task_name:"Lab Visit 1 Day 4 - Date"},
        "cl-v1-d4-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-v1-d4-date"},
        "cl-v1-d4-ksd-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-v1-d4-ksd",form_module:"cl-v1-d4-ksd-form",task_name:"Lab Visit 1 Day 4 - Karolinska Sleep Diary - File Upload"},
        "cl-v1-d4-ksd-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-v1-d4-ksd",task_name:"Karolinska Sleep Diary - File Upload"},
        "cl-v1-d4-ksd1-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-v1-d4-ksd1",form_module:"cl-v1-d4-ksd1-form",task_name:"Lab Visit 1 Day 4 - Karolinska Sleep Diary"},
        "cl-v1-d4-ksd1-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-v1-d4-ksd1",task_name:"Karolinska Sleep Diary"},
        "cl-v1-d4-hads-data":		                {url:"$H/m/library/hads-data.html",Table:"cl-v1-d4-hads",form_module:"cl-v1-d4-hads-form",task_name:"Lab Visit 1 Day 4 - HADS"},
        "cl-v1-d4-hads-form":		                {url:"$H/m/library/hads-form.html",Table:"cl-v1-d4-hads",task_name:"HADS"},

        "cl-v1-d4-nt-ftt-data":		            {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"cl-v1-d4-nt-ftt",form_module:"cl-v1-d4-nt-ftt-form",Table2:"cl-v1-d3-nt-ftt",task_name:"Lab Visit 1 Day 4 Neurocog Testing - FTT (6 mins)"},
        "cl-v1-d4-nt-ftt-form":		            {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"cl-v1-d4-nt-ftt",task_name:"FFT (6 mins"},

        "cl-v2-d1-t1-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d1-t1-kss",form_module:"cl-v2-d1-t1-kss-form",task_name:"Lab Visit 2 Day 1 - KSS 1"},
        "cl-v2-d1-t1-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d1-t1-kss",task_name:"KSS 1"},
        "cl-v2-d1-t1-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d1-t1-pvt",form_module:"cl-v2-d1-t1-pvt-form",task_name:"Lab Visit 2 Day 1 - PVT 1"},
        "cl-v2-d1-t1-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d1-t1-pvt"},
        "cl-v2-d1-t2-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d1-t2-kss",form_module:"cl-v2-d1-t2-kss-form",task_name:"Lab Visit 2 Day 1 - KSS 2"},
        "cl-v2-d1-t2-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d1-t2-kss",task_name:"KSS 2"},
        "cl-v2-d1-t2-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d1-t2-pvt",form_module:"cl-v2-d1-t2-pvt-form",task_name:"Lab Visit 2 Day 1 - PVT 2"},
        "cl-v2-d1-t2-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d1-t2-pvt"},
        "cl-v2-d1-t3-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d1-t3-kss",form_module:"cl-v2-d1-t3-kss-form",task_name:"Lab Visit 2 Day 1 - KSS 3"},
        "cl-v2-d1-t3-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d1-t3-kss",task_name:"KSS 3"},
        "cl-v2-d1-t3-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d1-t3-pvt",form_module:"cl-v2-d1-t3-pvt-form",task_name:"Lab Visit 2 Day 1 - PVT 3"},
        "cl-v2-d1-t3-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d1-t3-pvt"},
        "cl-v2-d1-t4-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d1-t4-kss",form_module:"cl-v2-d1-t4-kss-form",task_name:"Lab Visit 2 Day 1 - KSS 4"},
        "cl-v2-d1-t4-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d1-t4-kss",task_name:"KSS 4"},
        "cl-v2-d1-t4-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d1-t4-pvt",form_module:"cl-v2-d1-t4-pvt-form",task_name:"Lab Visit 2 Day 1 - PVT 4"},
        "cl-v2-d1-t4-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d1-t4-pvt"},
        "cl-v2-d1-t5-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d1-t5-kss",form_module:"cl-v2-d1-t5-kss-form",task_name:"Lab Visit 2 Day 1 - KSS 5"},
        "cl-v2-d1-t5-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d1-t5-kss",task_name:"KSS 5"},
        "cl-v2-d1-t5-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d1-t5-pvt",form_module:"cl-v2-d1-t5-pvt-form",task_name:"Lab Visit 2 Day 1 - PVT 5"},
        "cl-v2-d1-t5-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d1-t5-pvt"},
        "cl-v2-d2-t6-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d2-t6-kss",form_module:"cl-v2-d2-t6-kss-form",task_name:"Lab Visit 2 Day 2 - KSS 6"},
        "cl-v2-d2-t6-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d2-t6-kss",task_name:"KSS 6"},
        "cl-v2-d2-t6-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d2-t6-pvt",form_module:"cl-v2-d2-t6-pvt-form",task_name:"Lab Visit 2 Day 2 - PVT 6"},
        "cl-v2-d2-t6-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d2-t6-pvt"},
        "cl-v2-d2-t7-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d2-t7-kss",form_module:"cl-v2-d2-t7-kss-form",task_name:"Lab Visit 2 Day 2 - KSS 7"},
        "cl-v2-d2-t7-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d2-t7-kss",task_name:"KSS 7"},
        "cl-v2-d2-t7-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d2-t7-pvt",form_module:"cl-v2-d2-t7-pvt-form",task_name:"Lab Visit 2 Day 2 - PVT 7"},
        "cl-v2-d2-t7-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d2-t7-pvt"},
        "cl-v2-d2-t1-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d2-t1-kss",form_module:"cl-v2-d2-t1-kss-form",task_name:"Lab Visit 2 Day 2 - KSS 1"},
        "cl-v2-d2-t1-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d2-t1-kss",task_name:"KSS 1"},
        "cl-v2-d2-t1-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d2-t1-pvt",form_module:"cl-v2-d2-t1-pvt-form",task_name:"Lab Visit 2 Day 2 - PVT 1"},
        "cl-v2-d2-t1-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d2-t1-pvt"},
        "cl-v2-d2-t2-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d2-t2-kss",form_module:"cl-v2-d2-t2-kss-form",task_name:"Lab Visit 2 Day 2 - KSS 2"},
        "cl-v2-d2-t2-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d2-t2-kss",task_name:"KSS 2"},
        "cl-v2-d2-t2-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d2-t2-pvt",form_module:"cl-v2-d2-t2-pvt-form",task_name:"Lab Visit 2 Day 2 - PVT 2"},
        "cl-v2-d2-t2-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d2-t2-pvt"},
        "cl-v2-d2-t3-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d2-t3-kss",form_module:"cl-v2-d2-t3-kss-form",task_name:"Lab Visit 2 Day 2 - KSS 3"},
        "cl-v2-d2-t3-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d2-t3-kss",task_name:"KSS 3"},
        "cl-v2-d2-t3-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d2-t3-pvt",form_module:"cl-v2-d2-t3-pvt-form",task_name:"Lab Visit 2 Day 2 - PVT 3"},
        "cl-v2-d2-t3-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d2-t3-pvt"},
        "cl-v2-d2-t4-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d2-t4-kss",form_module:"cl-v2-d2-t4-kss-form",task_name:"Lab Visit 2 Day 2 - KSS 4"},
        "cl-v2-d2-t4-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d2-t4-kss",task_name:"KSS 4"},
        "cl-v2-d2-t4-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d2-t4-pvt",form_module:"cl-v2-d2-t4-pvt-form",task_name:"Lab Visit 2 Day 2 - PVT 4"},
        "cl-v2-d2-t4-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d2-t4-pvt"},
        "cl-v2-d2-t5-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d2-t5-kss",form_module:"cl-v2-d2-t5-kss-form",task_name:"Lab Visit 2 Day 2 - KSS 5"},
        "cl-v2-d2-t5-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d2-t5-kss",task_name:"KSS 5"},
        "cl-v2-d2-t5-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d2-t5-pvt",form_module:"cl-v2-d2-t5-pvt-form",task_name:"Lab Visit 2 Day 2 - PVT 5"},
        "cl-v2-d2-t5-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d2-t5-pvt"},
        "cl-v2-d3-t1-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d3-t1-kss",form_module:"cl-v2-d3-t1-kss-form",task_name:"Lab Visit 2 Day 3 - KSS 1"},
        "cl-v2-d3-t1-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d3-t1-kss",task_name:"KSS 1"},
        "cl-v2-d3-t1-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d3-t1-pvt",form_module:"cl-v2-d3-t1-pvt-form",task_name:"Lab Visit 2 Day 3 - PVT 1"},
        "cl-v2-d3-t1-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d3-t1-pvt"},
        "cl-v2-d3-t2-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d3-t2-kss",form_module:"cl-v2-d3-t2-kss-form",task_name:"Lab Visit 2 Day 3 - KSS 2"},
        "cl-v2-d3-t2-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d3-t2-kss",task_name:"KSS 2"},
        "cl-v2-d3-t2-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d3-t2-pvt",form_module:"cl-v2-d3-t2-pvt-form",task_name:"Lab Visit 2 Day 3 - PVT 2"},
        "cl-v2-d3-t2-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d3-t2-pvt"},
        "cl-v2-d3-t3-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d3-t3-kss",form_module:"cl-v2-d3-t3-kss-form",task_name:"Lab Visit 2 Day 3 - KSS 3"},
        "cl-v2-d3-t3-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d3-t3-kss",task_name:"KSS 3"},
        "cl-v2-d3-t3-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d3-t3-pvt",form_module:"cl-v2-d3-t3-pvt-form",task_name:"Lab Visit 2 Day 3 - PVT 3"},
        "cl-v2-d3-t3-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d3-t3-pvt"},
        "cl-v2-d3-t4-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d3-t4-kss",form_module:"cl-v2-d3-t4-kss-form",task_name:"Lab Visit 2 Day 3 - KSS 4"},
        "cl-v2-d3-t4-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d3-t4-kss",task_name:"KSS 4"},
        "cl-v2-d3-t4-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d3-t4-pvt",form_module:"cl-v2-d3-t4-pvt-form",task_name:"Lab Visit 2 Day 3 - PVT 4"},
        "cl-v2-d3-t4-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d3-t4-pvt"},
        "cl-v2-d3-t5-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d3-t5-kss",form_module:"cl-v2-d3-t5-kss-form",task_name:"Lab Visit 2 Day 3 - KSS 5"},
        "cl-v2-d3-t5-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d3-t5-kss",task_name:"KSS 5"},
        "cl-v2-d3-t5-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d3-t5-pvt",form_module:"cl-v2-d3-t5-pvt-form",task_name:"Lab Visit 2 Day 3 - PVT 5"},
        "cl-v2-d3-t5-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d3-t5-pvt"},
        "cl-v2-d3-t7-kdt-data":		            {url:"$H/m/library/file-location-data.html",Table:"cl-v2-d3-t7-kdt",form_module:"cl-v2-d3-t7-kdt-form",task_name:"Lab Visit 2 Day 3 - KDT 5"},
        "cl-v2-d3-t7-kdt-form":		            {url:"$H/m/library/file-location-form.html",Table:"cl-v2-d3-t7-kdt",task_name:"HdEEG KDT - Scoring report"},
        "cl-v2-d3-t6-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d3-t6-kss",form_module:"cl-v2-d3-t6-kss-form",task_name:"Lab Visit 2 Day 3 - KSS 6"},
        "cl-v2-d3-t6-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d3-t6-kss",task_name:"KSS 6"},
        "cl-v2-d3-t6-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d3-t6-pvt",form_module:"cl-v2-d3-t6-pvt-form",task_name:"Lab Visit 2 Day 3 - PVT 6"},
        "cl-v2-d3-t6-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d3-t6-pvt"},
        "cl-v2-d3-t7-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d3-t7-kss",form_module:"cl-v2-d3-t7-kss-form",task_name:"Lab Visit 2 Day 3 - KSS 7"},
        "cl-v2-d3-t7-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d3-t7-kss",task_name:"KSS 7"},
        "cl-v2-d3-t7-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d3-t7-pvt",form_module:"cl-v2-d3-t7-pvt-form",task_name:"Lab Visit 2 Day 3 - PVT 7"},
        "cl-v2-d3-t7-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d3-t7-pvt"},
        "cl-v2-d4-t1-kss-data":		            {url:"$H/m/library/kss-data.html",Table:"cl-v2-d4-t1-kss",form_module:"cl-v2-d4-t1-kss-form",task_name:"Lab Visit 2 Day 3 - KSS 1"},
        "cl-v2-d4-t1-kss-form":		            {url:"$H/m/library/kss-form.html",Table:"cl-v2-d4-t1-kss",task_name:"KSS 1"},
        "cl-v2-d4-t1-pvt-data":		            {url:"$H/m/library/pvt-data.html",Table:"cl-v2-d4-t1-pvt",form_module:"cl-v2-d4-t1-pvt-form",task_name:"Lab Visit 2 Day 3 - PVT 1"},
        "cl-v2-d4-t1-pvt-form":		            {url:"$H/m/library/pvt-form.html",Table:"cl-v2-d4-t1-pvt"},
        "cl-v2-d4-t1-kdt-data":		            {url:"$H/m/library/file-location-data.html",Table:"cl-v2-d4-t1-kdt",form_module:"cl-v2-d4-t1-kdt-form",task_name:"Lab Visit 2 Day 3 - KDT 1"},
        "cl-v2-d4-t1-kdt-form":		            {url:"$H/m/library/file-location-form.html",Table:"cl-v2-d4-t1-kdt",task_name:"HdEEG KDT - Scoring report"},

        "cl-v2-d1-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-v2-d1-date",form_module:"cl-v2-d1-date-form",task_name:"Lab Visit 2 Day 1 - Date"},
        "cl-v2-d1-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-v2-d1-date"},

        "cl-v2-d1-nt-bsrt2-data":		        {url:"$H/m/library/bsrt-data.html",Table:"cl-v2-d1-nt-bsrt",form_module:"cl-v2-d1-nt-bsrt2-form",task_name:"Lab Visit 2 Day 1 Neurocog Testing Set 2 - BSRT"},
        "cl-v2-d1-nt-bsrt2-form":		        {url:"$H/m/library/bsrt2-form.html",Table:"cl-v2-d1-nt-bsrt"},
        "cl-v2-d1-nt-lct-data":		            {url:"$H/m/neurocog/letter-cancellation-data.html",Table:"cl-v2-d1-nt-lct",form_module:"cl-v2-d1-nt-lct-form",task_name:"Lab Visit 2 Day 1 Neurocog Testing - LCT"},
        "cl-v2-d1-nt-lct-form":		            {url:"$H/m/neurocog/letter-cancellation-form.html",Table:"cl-v2-d1-nt-lct",task_name:"LCT"},
        "cl-v2-d1-nt-nback2-data":		        {url:"$H/m/neurocog/nback2-data.html",Table:"cl-v2-d1-nt-nback2",form_module:"cl-v2-d1-nt-nback2-form",task_name:"Lab Visit 2 Day 1 Neurocog Testing - 2-Back"},
        "cl-v2-d1-nt-nback2-form":		        {url:"$H/m/neurocog/nback2-form.html",Table:"cl-v2-d1-nt-nback2",task_name:"2-Back"},
        "cl-v2-d1-nt-dsst-data":		        {url:"$H/m/neurocog/dsst-data.html",Table:"cl-v2-d1-nt-dsst",form_module:"cl-v2-d1-nt-dsst-form",task_name:"Lab Visit 2 Day 1 Neurocog Testing - SDMT"},
        "cl-v2-d1-nt-dsst-form":		        {url:"$H/m/neurocog/dsst-form.html",Table:"cl-v2-d1-nt-dsst",task_name:"SDMT"},
        "cl-v2-d1-nt-stroop-text-data":		    {url:"$H/m/neurocog/stroop-text-data.html",Table:"cl-v2-d1-nt-stroop-text",form_module:"cl-v2-d1-nt-stroop-text-form",task_name:"Lab Visit 2 Day 1 Neurocog Testing - Stroop Text"},
        "cl-v2-d1-nt-stroop-text-form":		    {url:"$H/m/neurocog/stroop-text-form.html",Table:"cl-v2-d1-nt-stroop-text",task_name:"Stroop Text"},
        "cl-v2-d1-nt-stroop-colour-data":		{url:"$H/m/neurocog/stroop-colour-data.html",Table:"cl-v2-d1-nt-stroop-colour",form_module:"cl-v2-d1-nt-stroop-colour-form",task_name:"Lab Visit 2 Day 1 Neurocog Testing - Stroop Colour"},
        "cl-v2-d1-nt-stroop-colour-form":		{url:"$H/m/neurocog/stroop-colour-form.html",Table:"cl-v2-d1-nt-stroop-colour",task_name:"Stroop Colour"},
        "cl-v2-d1-nt-ftt-data":		            {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"cl-v2-d1-nt-ftt",form_module:"cl-v2-d1-nt-ftt-form",task_name:"Lab Visit 2 Day 1 Neurocog Testing - FTT (6 mins)"},
        "cl-v2-d1-nt-ftt-form":		            {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"cl-v2-d1-nt-ftt",task_name:"FFT (6 mins)"},

        "cl-v2-d2-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-v2-d2-date",form_module:"cl-v2-d2-date-form",task_name:"Lab Visit 2 Day 2 - Date"},
        "cl-v2-d2-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-v2-d2-date"},
        "cl-v2-d2-ksd-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-v2-d2-ksd",form_module:"cl-v2-d2-ksd-form",task_name:"Lab Visit 2 Day 2 - Karolinska Sleep Diary - File Upload"},
        "cl-v2-d2-ksd-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-v2-d2-ksd",task_name:"Karolinska Sleep Diary - File Upload"},
        "cl-v2-d2-ksd1-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-v2-d2-ksd1",form_module:"cl-v2-d2-ksd1-form",task_name:"Lab Visit 2 Day 2 - Karolinska Sleep Diary"},
        "cl-v2-d2-ksd1-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-v2-d2-ksd1",task_name:"Karolinska Sleep Diary"},

        "cl-v2-d3-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-v2-d3-date",form_module:"cl-v2-d3-date-form",task_name:"Lab Visit 2 Day 3 - Date"},
        "cl-v2-d3-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-v2-d3-date"},
        "cl-v2-d3-ksd-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-v2-d3-ksd",form_module:"cl-v2-d3-ksd-form",task_name:"Lab Visit 2 Day 3 - Karolinska Sleep Diary - File Upload"},
        "cl-v2-d3-ksd-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-v2-d3-ksd",task_name:"Karolinska Sleep Diary - File Upload"},
        "cl-v2-d3-ksd1-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-v2-d3-ksd1",form_module:"cl-v2-d3-ksd1-form",task_name:"Lab Visit 2 Day 3 - Karolinska Sleep Diary"},
        "cl-v2-d3-ksd1-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-v2-d3-ksd1",task_name:"Karolinska Sleep Diary"},

        "cl-v2-d3-ntm-lct-data":		            {url:"$H/m/neurocog/letter-cancellation-data.html",Table:"cl-v2-d3-ntm-lct",form_module:"cl-v2-d3-ntm-lct-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - LCT"},
        "cl-v2-d3-ntm-lct-form":		            {url:"$H/m/neurocog/letter-cancellation-form.html",Table:"cl-v2-d3-ntm-lct",task_name:"LCT"},
        "cl-v2-d3-ntm-nback2-data":		        {url:"$H/m/neurocog/nback2-data.html",Table:"cl-v2-d3-ntm-nback2",form_module:"cl-v2-d3-ntm-nback2-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - 2-Back"},
        "cl-v2-d3-ntm-nback2-form":		        {url:"$H/m/neurocog/nback2-form.html",Table:"cl-v2-d3-ntm-nback2",task_name:"2-Back"},
        "cl-v2-d3-ntm-dsst-data":		        {url:"$H/m/neurocog/dsst-data.html",Table:"cl-v2-d3-ntm-dsst",form_module:"cl-v2-d3-ntm-dsst-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - SDMT"},
        "cl-v2-d3-ntm-dsst-form":		        {url:"$H/m/neurocog/dsst-form.html",Table:"cl-v2-d3-ntm-dsst",task_name:"SDMT"},
        "cl-v2-d3-ntm-stroop-text-data":		    {url:"$H/m/neurocog/stroop-text-data.html",Table:"cl-v2-d3-ntm-stroop-text",form_module:"cl-v2-d3-ntm-stroop-text-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - Stroop Text"},
        "cl-v2-d3-ntm-stroop-text-form":		    {url:"$H/m/neurocog/stroop-text-form.html",Table:"cl-v2-d3-ntm-stroop-text",task_name:"Stroop Text"},
        "cl-v2-d3-ntm-stroop-colour-data":		{url:"$H/m/neurocog/stroop-colour-data.html",Table:"cl-v2-d3-ntm-stroop-colour",form_module:"cl-v2-d3-ntm-stroop-colour-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - Stroop Colour"},
        "cl-v2-d3-ntm-stroop-colour-form":		{url:"$H/m/neurocog/stroop-colour-form.html",Table:"cl-v2-d3-ntm-stroop-colour",task_name:"Stroop Colour"},

        "cl-v2-d3-nt-bsrt-data":		        {url:"$H/m/library/bsrt-data.html",Table:"cl-v2-d3-nt-bsrt",form_module:"cl-v2-d3-nt-bsrt-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing Set 1 - BSRT"},
        "cl-v2-d3-nt-bsrt-form":		        {url:"$H/m/library/bsrt-form.html",Table:"cl-v2-d3-nt-bsrt"},
        "cl-v2-d3-nt-lct-data":		            {url:"$H/m/neurocog/letter-cancellation-data.html",Table:"cl-v2-d3-nt-lct",form_module:"cl-v2-d3-nt-lct-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - LCT"},
        "cl-v2-d3-nt-lct-form":		            {url:"$H/m/neurocog/letter-cancellation-form.html",Table:"cl-v2-d3-nt-lct",task_name:"LCT"},
        "cl-v2-d3-nt-nback2-data":		        {url:"$H/m/neurocog/nback2-data.html",Table:"cl-v2-d3-nt-nback2",form_module:"cl-v2-d3-nt-nback2-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - 2-Back"},
        "cl-v2-d3-nt-nback2-form":		        {url:"$H/m/neurocog/nback2-form.html",Table:"cl-v2-d3-nt-nback2",task_name:"2-Back"},
        "cl-v2-d3-nt-dsst-data":		        {url:"$H/m/neurocog/dsst-data.html",Table:"cl-v2-d3-nt-dsst",form_module:"cl-v2-d3-nt-dsst-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - SDMT"},
        "cl-v2-d3-nt-dsst-form":		        {url:"$H/m/neurocog/dsst-form.html",Table:"cl-v2-d3-nt-dsst",task_name:"SDMT"},
        "cl-v2-d3-nt-stroop-text-data":		    {url:"$H/m/neurocog/stroop-text-data.html",Table:"cl-v2-d3-nt-stroop-text",form_module:"cl-v2-d3-nt-stroop-text-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - Stroop Text"},
        "cl-v2-d3-nt-stroop-text-form":		    {url:"$H/m/neurocog/stroop-text-form.html",Table:"cl-v2-d3-nt-stroop-text",task_name:"Stroop Text"},
        "cl-v2-d3-nt-stroop-colour-data":		{url:"$H/m/neurocog/stroop-colour-data.html",Table:"cl-v2-d3-nt-stroop-colour",form_module:"cl-v2-d3-nt-stroop-colour-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - Stroop Colour"},
        "cl-v2-d3-nt-stroop-colour-form":		{url:"$H/m/neurocog/stroop-colour-form.html",Table:"cl-v2-d3-nt-stroop-colour",task_name:"Stroop Colour"},
        "cl-v2-d3-nt-ftt-data":		            {url:"$H/m/neurocog/finger-tapping12-before-data.html",Table:"cl-v2-d3-nt-ftt",form_module:"cl-v2-d3-nt-ftt-form",task_name:"Lab Visit 2 Day 3 Neurocog Testing - FTT (12 mins)"},
        "cl-v2-d3-nt-ftt-form":		            {url:"$H/m/neurocog/finger-tapping12-before-form.html",Table:"cl-v2-d3-nt-ftt",task_name:"FFT (12 mins)"},

        "cl-v2-d4-date-data":		                {url:"$H/m/library/date-data.html",Table:"cl-v2-d4-date",form_module:"cl-v2-d4-date-form",task_name:"Lab Visit 2 Day 4 - Date"},
        "cl-v2-d4-date-form":		                {url:"$H/m/library/date-form.html",Table:"cl-v2-d4-date"},
        "cl-v2-d4-ksd-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-v2-d4-ksd",form_module:"cl-v2-d4-ksd-form",task_name:"Lab Visit 2 Day 4 - Karolinska Sleep Diary - File Upload"},
        "cl-v2-d4-ksd-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-v2-d4-ksd",task_name:"Karolinska Sleep Diary - File Upload"},
        "cl-v2-d4-ksd1-data":		            {url:"$H/m/library/ksd-data.html",Table:"cl-v2-d4-ksd1",form_module:"cl-v2-d4-ksd1-form",task_name:"Lab Visit 2 Day 4 - Karolinska Sleep Diary"},
        "cl-v2-d4-ksd1-form":		            {url:"$H/m/library/ksd-form.html",Table:"cl-v2-d4-ksd1",task_name:"Karolinska Sleep Diary"},
        "cl-v2-d4-hads-data":		                {url:"$H/m/library/hads-data.html",Table:"cl-v2-d4-hads",form_module:"cl-v2-d4-hads-form",task_name:"Lab Visit 2 Day 4 - HADS"},
        "cl-v2-d4-hads-form":		                {url:"$H/m/library/hads-form.html",Table:"cl-v2-d4-hads",task_name:"HADS"},

        "cl-v2-d4-nt-ftt-data":		            {url:"$H/m/neurocog/finger-tapping6-after-data.html",Table:"cl-v2-d4-nt-ftt",form_module:"cl-v2-d4-nt-ftt-form",Table2:"cl-v2-d3-nt-ftt",task_name:"Lab Visit 2 Day 4 Neurocog Testing - FTT (6 mins)"},
        "cl-v2-d4-nt-ftt-form":		            {url:"$H/m/neurocog/finger-tapping6-after-form.html",Table:"cl-v2-d4-nt-ftt",task_name:"FFT (6 mins)"},

        "word-pairs-set1-evening":	    {url:"$H/m/word-pairs/set1-evening.html"},
        "word-pairs-set2-evening":	    {url:"$H/m/word-pairs/set2-evening.html"},
        "word-pairs-set1-morning":	    {url:"$H/m/word-pairs/set1-morning.html"},
        "word-pairs-set2-morning":	    {url:"$H/m/word-pairs/set2-morning.html"},

        "cl-v2-d3-temperature-data":		    {url:"$H/m/library/temperature-data.html",Table:"cl-v2-d3-temperature",form_module:"cl-v2-d3-temperature-form",task_name:"Lab Visit 2 Day 3 HdEEG - Temperature"},
        "cl-v2-d3-temperature-form":		    {url:"$H/m/library/temperature-form.html",Table:"cl-v2-d3-temperature",task_name:"Temperature"},
        "cl-v2-d3-melatonin-data":		        {url:"$H/m/library/melatonin-data.html",Table:"cl-v2-d3-melatonin",form_module:"cl-v2-d3-melatonin-form",task_name:"Lab Visit 2 Day 3 HdEEG - Melatonin"},
        "cl-v2-d3-melatonin-form":		        {url:"$H/m/library/melatonin-form.html",Table:"cl-v2-d3-melatonin",task_name:"Melatonin"},
        "cl-v2-d3-psg300-data":		            {url:"$H/m/library/psg300-data.html",Table:"cl-v2-d3-psg300",form_module:"cl-v2-d3-psg300-form",task_name:"Lab Visit 2 Day 3 HdEEG - PSG - Report"},
        "cl-v2-d3-psg300-form":		            {url:"$H/m/library/psg300-form.html",Table:"cl-v2-d3-psg300",task_name:"PSG - Report"},
        "cl-v2-d3-sleep-scoring-data":		    {url:"$H/m/library/upload-file-data.html",Table:"cl-v2-d3-sleep-scoring",form_module:"cl-v2-d3-sleep-scoring-form",task_name:"Lab Visit 2 Day 3 HdEEG - PSG - Sleep Scoring"},
        "cl-v2-d3-sleep-scoring-form":		    {url:"$H/m/library/upload-file-form.html",Table:"cl-v2-d3-sleep-scoring",task_name:"PSG - Sleep Scoring"},
        "cl-v2-d3-edf-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-v2-d3-edf",form_module:"cl-v2-d3-edf-form",task_name:"Lab Visit 2 Day 3 HdEEG - PSG - EDF"},
        "cl-v2-d3-edf-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-v2-d3-edf",task_name:"PSG - EDF"},

        "cl-v1-d3-temperature-data":		    {url:"$H/m/library/temperature-data.html",Table:"cl-v1-d3-temperature",form_module:"cl-v1-d3-temperature-form",task_name:"Lab Visit 1 Day 3 HdEEG - Temperature"},
        "cl-v1-d3-temperature-form":		    {url:"$H/m/library/temperature-form.html",Table:"cl-v1-d3-temperature",task_name:"Temperature"},
        "cl-v1-d3-melatonin-data":		        {url:"$H/m/library/melatonin-data.html",Table:"cl-v1-d3-melatonin",form_module:"cl-v1-d3-melatonin-form",task_name:"Lab Visit 1 Day 3 HdEEG - Melatonin"},
        "cl-v1-d3-melatonin-form":		        {url:"$H/m/library/melatonin-form.html",Table:"cl-v1-d3-melatonin",task_name:"Melatonin"},
        "cl-v1-d3-psg300-data":		            {url:"$H/m/library/psg300-data.html",Table:"cl-v1-d3-psg300",form_module:"cl-v1-d3-psg300-form",task_name:"Lab Visit 1 Day 3 HdEEG - PSG - Report"},
        "cl-v1-d3-psg300-form":		            {url:"$H/m/library/psg300-form.html",Table:"cl-v1-d3-psg300",task_name:"PSG - Report"},
        "cl-v1-d3-sleep-scoring-data":		    {url:"$H/m/library/upload-file-data.html",Table:"cl-v1-d3-sleep-scoring",form_module:"cl-v1-d3-sleep-scoring-form",task_name:"Lab Visit 1 Day 3 HdEEG - PSG - Sleep Scoring"},
        "cl-v1-d3-sleep-scoring-form":		    {url:"$H/m/library/upload-file-form.html",Table:"cl-v1-d3-sleep-scoring",task_name:"PSG - Sleep Scoring"},
        "cl-v1-d3-edf-data":		            {url:"$H/m/library/upload-file-data.html",Table:"cl-v1-d3-edf",form_module:"cl-v1-d3-edf-form",task_name:"Lab Visit 1 Day 3 HdEEG - PSG - EDF"},
        "cl-v1-d3-edf-form":		            {url:"$H/m/library/upload-file-form.html",Table:"cl-v1-d3-edf",task_name:"PSG - EDF"},

        "cl-v1-d1-t1-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v1-d1-t1-nt-wp",form_module:"cl-v1-d1-t1-nt-wp-form",task_name:"Lab Visit 1 Day 1 Trial 1 Word Pair - Data entry"},
        "cl-v1-d1-t1-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v1-d1-t1-nt-wp",task_name:"Word Pair Trial 1 - Data entry"},
        "cl-v1-d1-t2-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v1-d1-t2-nt-wp",form_module:"cl-v1-d1-t2-nt-wp-form",task_name:"Lab Visit 1 Day 1 Trial 2 Word Pair - Data entry"},
        "cl-v1-d1-t2-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v1-d1-t2-nt-wp",task_name:"Word Pair Trial 2 - Data entry"},
        "cl-v1-d1-t3-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v1-d1-t3-nt-wp",form_module:"cl-v1-d1-t3-nt-wp-form",task_name:"Lab Visit 1 Day 1 Trial 3 Word Pair - Data entry"},
        "cl-v1-d1-t3-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v1-d1-t3-nt-wp",task_name:"Word Pair Trial 3 - Data entry"},
        "cl-v1-d3-t1-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v1-d3-t1-nt-wp",form_module:"cl-v1-d3-t1-nt-wp-form",task_name:"Lab Visit 1 Day 3 Trial 1 Word Pair - Data entry"},
        "cl-v1-d3-t1-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v1-d3-t1-nt-wp",task_name:"Word Pair Trial 1 - Data entry"},
        "cl-v1-d3-t2-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v1-d3-t2-nt-wp",form_module:"cl-v1-d3-t2-nt-wp-form",task_name:"Lab Visit 1 Day 3 Trial 2 Word Pair - Data entry"},
        "cl-v1-d3-t2-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v1-d3-t2-nt-wp",task_name:"Word Pair Trial 2 - Data entry"},
        "cl-v1-d3-t3-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v1-d3-t3-nt-wp",form_module:"cl-v1-d3-t3-nt-wp-form",task_name:"Lab Visit 1 Day 3 Trial 3 Word Pair - Data entry"},
        "cl-v1-d3-t3-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v1-d3-t3-nt-wp",task_name:"Word Pair Trial 3 - Data entry"},
        "cl-v1-d4-nt-wp-data":		            {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v1-d4-nt-wp",form_module:"cl-v1-d4-nt-wp-form",task_name:"Lab Visit 1 Day 4 Word Pair - Data entry"},
        "cl-v1-d4-nt-wp-form":		            {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v1-d4-nt-wp",task_name:"Word Pair - Data entry"},
        "cl-v2-d1-t1-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v2-d1-t1-nt-wp",form_module:"cl-v2-d1-t1-nt-wp-form",task_name:"Lab Visit 2 Day 1 Trial 1 Word Pair - Data entry"},
        "cl-v2-d1-t1-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v2-d1-t1-nt-wp",task_name:"Word Pair Trial 1 - Data entry"},
        "cl-v2-d1-t2-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v2-d1-t2-nt-wp",form_module:"cl-v2-d1-t2-nt-wp-form",task_name:"Lab Visit 2 Day 1 Trial 2 Word Pair - Data entry"},
        "cl-v2-d1-t2-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v2-d1-t2-nt-wp",task_name:"Word Pair Trial 2 - Data entry"},
        "cl-v2-d1-t3-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v2-d1-t3-nt-wp",form_module:"cl-v2-d1-t3-nt-wp-form",task_name:"Lab Visit 2 Day 1 Trial 3 Word Pair - Data entry"},
        "cl-v2-d1-t3-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v2-d1-t3-nt-wp",task_name:"Word Pair Trial 3 - Data entry"},
        "cl-v2-d3-t1-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v2-d3-t1-nt-wp",form_module:"cl-v2-d3-t1-nt-wp-form",task_name:"Lab Visit 2 Day 3 Trial 1 Word Pair - Data entry"},
        "cl-v2-d3-t1-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v2-d3-t1-nt-wp",task_name:"Word Pair Trial 1 - Data entry"},
        "cl-v2-d3-t2-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v2-d3-t2-nt-wp",form_module:"cl-v2-d3-t2-nt-wp-form",task_name:"Lab Visit 2 Day 3 Trial 2 Word Pair - Data entry"},
        "cl-v2-d3-t2-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v2-d3-t2-nt-wp",task_name:"Word Pair Trial 2 - Data entry"},
        "cl-v2-d3-t3-nt-wp-data":		        {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v2-d3-t3-nt-wp",form_module:"cl-v2-d3-t3-nt-wp-form",task_name:"Lab Visit 2 Day 3 Trial 3 Word Pair - Data entry"},
        "cl-v2-d3-t3-nt-wp-form":		        {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v2-d3-t3-nt-wp",task_name:"Word Pair Trial 3 - Data entry"},
        "cl-v2-d4-nt-wp-data":		            {url:"$H/m/library/word-pair-task-paperwork-data.html",Table:"cl-v2-d4-nt-wp",form_module:"cl-v2-d4-nt-wp-form",task_name:"Lab Visit 2 Day 4 Word Pair - Data entry"},
        "cl-v2-d4-nt-wp-form":		            {url:"$H/m/library/word-pair-task-paperwork-form.html",Table:"cl-v2-d4-nt-wp",task_name:"Word Pair - Data entry"},
    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
    if(window.location.toString().indexOf('tb=demo')!=-1){
        for(p in $vm.module_list){
            $vm.module_list[p].Table="demo-"+$vm.module_list[p].Table;
        }
    }

})();
